name: Build wheels

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  build_dist:
    name: Build wheels and source distributions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-20.04, windows-2019, macos-11]
    steps:
      - uses: actions/checkout@v3

      - name: Build sdist
        run: pipx run build

      - uses: actions/upload-artifact@v3
        with:
          path: dist/*

  upload_pypi:
    needs: [build_dist]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          # unpacks default artifact into dist/
          # if `name: artifact` is omitted, the action will create extra parent dir
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.5.0
        with:
          user: __token__
          password: ${{ secrets.pypi_password }}
          #repository_url: https://test.pypi.org/legacy/
