name: pdoc

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: 1.1.11
      - name: install dependencies
        run: |
          poetry install
          poetry run pip install ghp-import
      - name: build docs
        run: |
          poetry run pdoc preconstruct -o docs
      - name: push docs
        run: |
          poetry run ghp-import -nfop docs
